package com.sabbirsamol.app

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.widget.Toast
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.database.FirebaseDatabase

class GoogleAuthActivity : Activity() {

    private val auth by lazy { FirebaseAuth.getInstance() }
    private val database by lazy { FirebaseDatabase.getInstance().reference }
    private lateinit var googleSignInClient: GoogleSignInClient

    companion object {
        private const val RC_GOOGLE_SIGN_IN = 1001
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Use the OAuth Web Client ID generated by Firebase/Google Services.
        val webClientId = "87832154927-ihigonb4tvml9qaulms5bbipt8lkoaqj.apps.googleusercontent.com"
        val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId)
            .requestEmail()
            .build()

        googleSignInClient = GoogleSignIn.getClient(this, options)
        startActivityForResult(googleSignInClient.signInIntent, RC_GOOGLE_SIGN_IN)
    }

    @Deprecated("Deprecated in Android SDK, retained for compatibility with this project.")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode != RC_GOOGLE_SIGN_IN) return

        if (resultCode != RESULT_OK || data == null) {
            Toast.makeText(this, "Google লগইন বাতিল করা হয়েছে।", Toast.LENGTH_SHORT).show()
            finish()
            return
        }

        try {
            val account = GoogleSignIn.getSignedInAccountFromIntent(data)
                .getResult(ApiException::class.java)

            val idToken = account.idToken
            if (idToken.isNullOrBlank()) {
                Toast.makeText(this, "Google Account Token পাওয়া যায়নি।", Toast.LENGTH_LONG).show()
                finish()
                return
            }

            signInToFirebase(idToken, account.email, account.displayName)
        } catch (e: ApiException) {
            Toast.makeText(this, "Google লগইন ব্যর্থ: ${e.message ?: "অজানা সমস্যা"}", Toast.LENGTH_LONG).show()
            finish()
        }
    }

    private fun signInToFirebase(idToken: String, email: String?, displayName: String?) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)

        auth.signInWithCredential(credential)
            .addOnSuccessListener { result ->
                val user = result.user

                if (user == null) {
                    Toast.makeText(this, "Google ব্যবহারকারীর তথ্য পাওয়া যায়নি।", Toast.LENGTH_LONG).show()
                    finish()
                    return@addOnSuccessListener
                }

                val savedEmail = user.email ?: email.orEmpty()
                val savedName = user.displayName ?: displayName.orEmpty()
                val uid = user.uid

                getSharedPreferences("AppSettings", MODE_PRIVATE).edit()
                    .putString("user_uid", uid)
                    .putString("user_email", savedEmail)
                    .putString("user_name", savedName)
                    .remove("user_mobile")
                    .apply()

                val userData = mapOf(
                    "firebase_uid" to uid,
                    "email" to savedEmail,
                    "display_name" to savedName,
                    "login_provider" to "google"
                )

                database.child("users").child(uid).updateChildren(userData)
                    .addOnCompleteListener {
                        Toast.makeText(
                            this,
                            if (savedEmail.isNotBlank()) "Google Account দিয়ে লগইন সফল।\n$savedEmail"
                            else "Google Account দিয়ে লগইন সফল।",
                            Toast.LENGTH_LONG
                        ).show()
                        finish()
                    }
            }
            .addOnFailureListener { e ->
                Toast.makeText(
                    this,
                    "Firebase লগইন ব্যর্থ: ${e.message ?: "অজানা সমস্যা"}",
                    Toast.LENGTH_LONG
                ).show()
                finish()
            }
    }
}
